import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { Header } from "../components/Header";

const poppins = Poppins({ subsets: ["latin"], weight:'400'});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={poppins.className}>
        <div className="w-screen bg-teal-300 flex items-center justify-center flex-col">
          <Header />
          <main className="bg-blue-500 flex flex-1 flex-col max-w-6xl">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
